name: 1.0.$(myBuildCounter)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: "NuGet Feed credentials"
- name: myBuildCounter
  value: $[counter('buildCounter',27)]

steps:

- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '**/Docker/Dockerfile'
    repository: lh_mocka
    tags: '$(Build.BuildNumber)'